name: frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test -- --coverage

      - name: Upload jest test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: jest-results-1.20
          path: ./coverage/lcov-report/index.html
          retention-days: 5
